source "https://rubygems.org"

ruby "3.3.6"

gem "rails", "~> 7.2.2"
gem "pg", "~> 1.5"
gem "puma", ">= 6.4"
gem "rack-cors", "~> 2.0"
gem "bootsnap", ">= 1.18", require: false
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.9"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end

